-- This script runs automatically on first Oracle container initialization.
-- Add additional DDL files in this folder using lexicographic naming (01_, 02_, ...).

ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLE etl_pipeline_audit (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pipeline_name   VARCHAR2(100) NOT NULL,
    stage_name      VARCHAR2(50) NOT NULL,
    status          VARCHAR2(20) NOT NULL,
    start_time      TIMESTAMP,
    end_time        TIMESTAMP,
    message         VARCHAR2(1000),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
